### ISSUE TITLE
Tournaments are not distinctly separated by participation and ownership in view

### ISSUE THREAD

**Issue by gumbogal** [sjohnston00/HotshotTournaments#24]
When viewing the My Tournaments page, there doesn't seem to be a visual queue to understand which tournaments the user is the _creator_ of and which they are simply _participating_ in. This is confusing.

![image](https://user-images.githubusercontent.com/15250241/112214611-4da92800-8c17-11eb-81fc-8f8e44ad0e4f.png)

**Comment by sjohnston00** [comment]
Yeah that's a good shout 👍🏼
