### ISSUE TITLE
When deleting a tournament, an error message toast is sent to the view, even though the tournament is successfully deleted

### ISSUE THREAD

**Issue by gumbogal** [sjohnston00/HotshotTournaments#5]
This occurs in the[ delete_tournament method](https://github.com/sjohnston00/HotshotTournaments/blob/Implement-controllers/src/controllers/tournamentsController.js#L377) of the tournament controller. I think it specifically only occurs for tournaments which have no messages, so that when we query the database for messages on line [392](https://github.com/sjohnston00/HotshotTournaments/blob/Implement-controllers/src/controllers/tournamentsController.js#L392), it can't find anything and thus returns an error. If this is the case then it'll will be an easy fix.

**Comment by sjohnston00** [comment]
Okay seems like an easy fix 👍🏼

**Comment by gumbogal** [comment]
When removing the deleteMany query it works, so that is definitely the offending line. I just need to find the best way to trigger that only when necessary.
